spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: Account123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
  hibernate:
    ddl-auto: update
app:
  superuser: superuser@gmail.com
  password: Super@123
  jwt-secret: adfasdf23423423423fdsafsdfasdfasdfasdf
